[package]
name = "rusty-journal"
version = "0.2.0"
edition = "2021"


[dependencies]
colored = "2.0.0"
anyhow = "1.0"
home = "0.5.4"
serde_json = "1.0"   
structopt = "0.3.26"

[dependencies.chrono]
features = ["serde"] 
version = "0.4.23"

[dependencies.serde] 
features = ["derive"]
version = "1.0"